const test=require('node:test');const assert=require('node:assert/strict');const {generateKeyPairSync,sign}=require('node:crypto');
const {verifyToken,AUDIENCE}=require('../lib/operations-auth');
const {publicKey,privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});const jwk={...publicKey.export({format:'jwk'}),kid:'test',alg:'RS256'};const now=1800000000;
const valid={iss:'https://token.actions.githubusercontent.com',aud:AUDIENCE,sub:'repo:thomaschurchadams-eng/work-feel:ref:refs/heads/main',repository:'thomaschurchadams-eng/work-feel',repository_id:'1086718496',repository_owner_id:'241192016',ref:'refs/heads/main',workflow_ref:'thomaschurchadams-eng/work-feel/.github/workflows/cuai-operations.yml@refs/heads/main',runner_environment:'github-hosted',event_name:'deployment_status',iat:now,nbf:now,exp:now+300,run_id:'123'};
const token=(claims=valid,header={alg:'RS256',kid:'test',typ:'JWT'})=>{const body=[header,claims].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.');return body+'.'+sign('RSA-SHA256',Buffer.from(body),privateKey).toString('base64url');};
test('only the exact trusted workflow receives authorization',async()=>{assert.equal((await verifyToken(token(),async()=>[jwk],now)).runId,'123');for(const change of [{aud:'wrong'},{repository_id:'9'},{repository_owner_id:'9'},{ref:'refs/pull/1/merge'},{event_name:'pull_request'},{workflow_ref:'other'},{sub:'other'},{exp:now-1},{iat:now-1000},{nbf:now+100},{runner_environment:'self-hosted'}])await assert.rejects(verifyToken(token({...valid,...change}),async()=>[jwk],now));});
test('signature, algorithm and key failures reject the token',async()=>{for(const bad of ['', 'public-commit-sha',token().slice(0,-5)+'abcde',token(valid,{alg:'none',kid:'test'})])await assert.rejects(verifyToken(bad,async()=>[jwk],now));await assert.rejects(verifyToken(token(),async()=>[],now));});
test('all endpoints reject public SHA-only calls before any downstream request',async()=>{let calls=0;const saved=global.fetch;global.fetch=async()=>{calls++;throw Error('Unexpected external request');};try{for(const name of ['buffer-schedule','buffer-schedule-image','buffer-schedule-tracked','buffer-metrics','ga4-metrics','search-console-metrics','operations-health']){const handler=require('../api/'+name);let status,result;const response={setHeader(){},status(value){status=value;return this;},json(value){result=value;return this;}};await handler({method:'POST',headers:{},query:{commitSha:'public'},body:{commitSha:'public'}},response);assert.equal(status,401,name);assert.equal(result.ok,false);}assert.equal(calls,0);}finally{global.fetch=saved;}});
const vm=require('node:vm');const fs=require('node:fs');
const runner=fs.readFileSync(require('node:path').join(__dirname,'../scripts/run-secure-operations.cjs'),'utf8');
async function runWorkflow({moved=false,healthFailure=false,timeout=false,queued=false,noReceipt=false,queueChanged=false}={}){
 const sha='a'.repeat(40),calls=[],files={};const item={id:'linkedin-test',status:'queued',scheduledFor:new Date(Date.now()+86400000).toISOString(),articleUrl:'https://creditunionainews.com/article',copy:'example'};
 const fakeFs={mkdirSync(){},writeFileSync(path,value){files[path]=value;},readFileSync(){return JSON.stringify({items:queued?[item]:[]});}};
 const processStub={env:{DEPLOYED_SHA:sha,GITHUB_TOKEN:'github-fixture',ACTIONS_ID_TOKEN_REQUEST_URL:'https://identity.example/token',ACTIONS_ID_TOKEN_REQUEST_TOKEN:'fixture'}};
 const fetcher=async(url,options={})=>{calls.push({url:String(url),options});let body={ok:true};
 if(String(url).endsWith('/commits/main'))body={sha:moved?'b'.repeat(40):sha};
 else if(String(url).startsWith('https://identity.example/'))body={value:'signed-fixture'};
 else if(String(url).endsWith('/operations-health'))body=healthFailure?{ok:false}:{ok:true,commit:sha,environment:'production'};
 else if(String(url).includes('/contents/automation/social-queue.json')&&options.method!=='PUT')body={sha:'queue-version',content:Buffer.from(JSON.stringify({items:[{...item,...(queueChanged?{copy:'Changed after scheduling'}:{})},{id:'untouched',status:'sent'}]})).toString('base64')};
 else if(String(url).includes('/api/')){assert.equal(options.method,'POST');assert.equal(options.headers.Authorization,'Bearer signed-fixture');assert.equal(JSON.parse(options.body).commitSha,sha);if(String(url).endsWith('/buffer-schedule-tracked')){if(timeout)throw Error('ambiguous timeout');if(!noReceipt)body={ok:true,postId:'buffer-receipt',status:'scheduled'};}}
 return {ok:true,status:200,json:async()=>body};};
 await vm.runInNewContext(runner,{require:name=>name==='node:fs'?fakeFs:require(name),process:processStub,fetch:fetcher,URL,AbortSignal,Buffer,Date,console:{log(){},error(){}}});
 return {calls,files,process:processStub};
}
test('workflow verifies current production identity before source or action calls',async()=>{const normal=await runWorkflow();assert.equal(normal.calls.filter(c=>c.url.includes('/api/')).length,4);assert.equal(JSON.parse(normal.files['operation-receipts/run.json']).authentication,'verified');for(const options of [{moved:true},{healthFailure:true}]){const result=await runWorkflow(options);assert.equal(result.calls.some(c=>c.url.endsWith('/buffer-schedule-tracked')),false);assert.equal(result.calls.some(c=>c.url.endsWith('/ga4-metrics')),false);}});
test('ambiguous scheduling outcome is recorded without a blind retry or queue rewrite',async()=>{const result=await runWorkflow({timeout:true,queued:true});assert.equal(result.calls.filter(c=>c.url.endsWith('/buffer-schedule-tracked')).length,1);assert.equal(result.calls.some(c=>c.options.method==='PUT'),false);assert.equal(JSON.parse(result.files['operation-receipts/run.json']).status,'failed');assert.equal(result.process.exitCode,1);});
test('queue writes require a real receipt and unchanged reserved content',async()=>{const accepted=await runWorkflow({queued:true});const writes=accepted.calls.filter(c=>c.options.method==='PUT');assert.equal(writes.length,1);const put=JSON.parse(writes[0].options.body);assert.equal(put.sha,'queue-version');const updated=JSON.parse(Buffer.from(put.content,'base64').toString());assert.equal(updated.items[0].postId,'buffer-receipt');assert.deepEqual(updated.items[1],{id:'untouched',status:'sent'});for(const option of [{noReceipt:true},{queueChanged:true}]){const result=await runWorkflow({queued:true,...option});assert.equal(result.calls.some(c=>c.options.method==='PUT'),false);assert.equal(result.process.exitCode,1);}});
